// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class tbCargos
    {
        public tbCargos()
        {
            tbEmpleados = new HashSet<tbEmpleados>();
        }

        public int carg_Id { get; set; }
        public string carg_Nombre { get; set; }
        public bool? carg_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? carg_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? carg_FechaModificacion { get; set; }

        public virtual tbUsuarios usua_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleados { get; set; }
    }
}