// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class tbClientes
    {
        public tbClientes()
        {
            tbCitas = new HashSet<tbCitas>();
            tbDireccionesPorCliente = new HashSet<tbDireccionesPorCliente>();
            tbEnvios = new HashSet<tbEnvios>();
            tbFacturas = new HashSet<tbFacturas>();
            tbOrdenes = new HashSet<tbOrdenes>();
        }

        public int clie_Id { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_Apellidos { get; set; }
        public string clie_Identidad { get; set; }
        public string clie_Sexo { get; set; }
        public DateTime clie_FechaNacimiento { get; set; }
        public int estacivi_Id { get; set; }
        public string clie_Telefono { get; set; }
        public string clie_CorreoElectronico { get; set; }
        public int dire_Id { get; set; }
        public int clie_UsuCreacion { get; set; }
        public DateTime clie_FechaCreacion { get; set; }
        public int? clie_UsuModificacion { get; set; }
        public DateTime? clie_FechaModificacion { get; set; }
        public bool? clie_Estado { get; set; }

        public virtual tbUsuarios clie_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios clie_UsuModificacionNavigation { get; set; }
        public virtual tbDirecciones dire { get; set; }
        public virtual tbEstadosCiviles estacivi { get; set; }
        public virtual ICollection<tbCitas> tbCitas { get; set; }
        public virtual ICollection<tbDireccionesPorCliente> tbDireccionesPorCliente { get; set; }
        public virtual ICollection<tbEnvios> tbEnvios { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
        public virtual ICollection<tbOrdenes> tbOrdenes { get; set; }
    }
}