// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class tbConsultorios
    {
        public tbConsultorios()
        {
            tbCitas = new HashSet<tbCitas>();
        }

        public int cons_Id { get; set; }
        public string cons_Nombre { get; set; }
        public int empe_Id { get; set; }
        public bool? cons_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? cons_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? cons_FechaModificacion { get; set; }

        [NotMapped]
        public string sucu_Descripcion { get; set; }

        [NotMapped]
        public string empe_Nombres { get; set; }

        public virtual tbEmpleados empe { get; set; }
        public virtual tbUsuarios usua_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbCitas> tbCitas { get; set; }
    }
}