// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class tbDetallesOrdenes
    {
        public int deor_Id { get; set; }
        public int orde_Id { get; set; }
        public int aros_Id { get; set; }
        public string deor_GraduacionLeft { get; set; }
        public string deor_GraduacionRight { get; set; }
        public decimal deor_Precio { get; set; }
        public int deor_Cantidad { get; set; }
        public decimal deor_Total { get; set; }
        public bool? deor_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? orde_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? orde_FechaModificacion { get; set; }

        public virtual tbAros aros { get; set; }
        public virtual tbOrdenes orde { get; set; }
        public virtual tbUsuarios usua_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_IdModificacionNavigation { get; set; }
    }
}