// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class tbDetallesFactura
    {
        public int defa_Id { get; set; }
        public int fact_Id { get; set; }
        public int? orde_Id { get; set; }
        public int? envi_Id { get; set; }
        public decimal defa_Total { get; set; }
        public bool? defa_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? defa_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? defa_FechaModificacion { get; set; }

        public virtual tbEnvios envi { get; set; }
        public virtual tbFacturas fact { get; set; }
        public virtual tbOrdenes orde { get; set; }
        public virtual tbUsuarios usua_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_IdModificacionNavigation { get; set; }
    }
}