// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class tbEnvios
    {
        public tbEnvios()
        {
            tbDetallesEnvios = new HashSet<tbDetallesEnvios>();
        }

        public int envi_Id { get; set; }
        public int clie_Id { get; set; }
        public int dire_Id { get; set; }
        public DateTime? envi_Fecha { get; set; }
        public DateTime envi_FechaEntrega { get; set; }
        public DateTime envi_FechaEntregaReal { get; set; }
        public bool? clie_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? clie_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? clie_FechaModificacion { get; set; }

        public virtual tbClientes clie { get; set; }
        public virtual tbDirecciones dire { get; set; }
        public virtual tbUsuarios usua_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbDetallesEnvios> tbDetallesEnvios { get; set; }
    }
}