// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class tbFacturas
    {
        public tbFacturas()
        {
            tbDetallesFactura = new HashSet<tbDetallesFactura>();
            tbEnvios = new HashSet<tbEnvios>();
        }

        public int fact_Id { get; set; }
        public int? cita_Id { get; set; }
        public DateTime? fact_Fecha { get; set; }
        public int meto_Id { get; set; }
        public int empe_Id { get; set; }
        public decimal fact_Total { get; set; }
        public bool? fact_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? fact_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? fact_FechaModificacion { get; set; }

        [NotMapped]
        public string meto_Nombre { get; set; }

        [NotMapped]
        public string empe_Nombres { get; set; }

        [NotMapped]
        public string empe_Apellidos { get; set; }

        public virtual tbCitas cita { get; set; }
        public virtual tbEmpleados empe { get; set; }
        public virtual tbMetodosPago meto { get; set; }
        public virtual tbUsuarios usua_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbDetallesFactura> tbDetallesFactura { get; set; }
        public virtual ICollection<tbEnvios> tbEnvios { get; set; }
    }
}