// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class tbMarcas
    {
        public tbMarcas()
        {
            tbAros = new HashSet<tbAros>();
        }

        public int marc_Id { get; set; }
        public string marc_Nombre { get; set; }
        public bool? marc_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? marc_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? marc_FechaModificacion { get; set; }

        public virtual tbUsuarios usua_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbAros> tbAros { get; set; }
    }
}