// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class tbStockArosPorSucursal
    {
        public int stsu_Id { get; set; }
        public int sucu_Id { get; set; }
        public int aros_Id { get; set; }
        public int stsu_Stock { get; set; }
        public bool? stsu_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? stsu_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? stsu_FechaModificacion { get; set; }

        public virtual tbAros aros { get; set; }
        public virtual tbSucursales sucu { get; set; }
        public virtual tbUsuarios usua_IdCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_IdModificacionNavigation { get; set; }
    }
}