// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            Inverseusua_UsuCreacionNavigation = new HashSet<tbUsuarios>();
            Inverseusua_UsuModificacionNavigation = new HashSet<tbUsuarios>();
            tbArosaros_UsuCreacionNavigation = new HashSet<tbAros>();
            tbArosaros_UsuModificacionNavigation = new HashSet<tbAros>();
            tbCargoscarg_UsuCreacionNavigation = new HashSet<tbCargos>();
            tbCargoscarg_UsuModificacionNavigation = new HashSet<tbCargos>();
            tbCategoriascate_UsuCreacionNavigation = new HashSet<tbCategorias>();
            tbCategoriascate_UsuModificacionNavigation = new HashSet<tbCategorias>();
            tbCitasusua_IdCreacionNavigation = new HashSet<tbCitas>();
            tbCitasusua_IdModificacionNavigation = new HashSet<tbCitas>();
            tbClientesclie_UsuCreacionNavigation = new HashSet<tbClientes>();
            tbClientesclie_UsuModificacionNavigation = new HashSet<tbClientes>();
            tbConsultoriosusua_IdCreacionNavigation = new HashSet<tbConsultorios>();
            tbConsultoriosusua_IdModificacionNavigation = new HashSet<tbConsultorios>();
            tbDepartamentosdepa_UsuCreacionNavigation = new HashSet<tbDepartamentos>();
            tbDepartamentosdepa_UsuModificacionNavigation = new HashSet<tbDepartamentos>();
            tbDetallesCitasusua_IdCreacionNavigation = new HashSet<tbDetallesCitas>();
            tbDetallesCitasusua_IdModificacionNavigation = new HashSet<tbDetallesCitas>();
            tbDetallesEnviosusua_IdCreacionNavigation = new HashSet<tbDetallesEnvios>();
            tbDetallesEnviosusua_IdModificacionNavigation = new HashSet<tbDetallesEnvios>();
            tbDetallesOrdenesusua_IdCreacionNavigation = new HashSet<tbDetallesOrdenes>();
            tbDetallesOrdenesusua_IdModificacionNavigation = new HashSet<tbDetallesOrdenes>();
            tbDireccionesPorClienteusua_IdCreacionNavigation = new HashSet<tbDireccionesPorCliente>();
            tbDireccionesPorClienteusua_IdModificacionNavigation = new HashSet<tbDireccionesPorCliente>();
            tbDireccionesusua_IdCreacionNavigation = new HashSet<tbDirecciones>();
            tbDireccionesusua_IdModificacionNavigation = new HashSet<tbDirecciones>();
            tbEmpleadosempe_UsuCreacionNavigation = new HashSet<tbEmpleados>();
            tbEmpleadosempe_UsuModificacionNavigation = new HashSet<tbEmpleados>();
            tbEnviosusua_IdCreacionNavigation = new HashSet<tbEnvios>();
            tbEnviosusua_IdModificacionNavigation = new HashSet<tbEnvios>();
            tbEstadosCivilesestacivi_UsuCreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesestacivi_UsuModificacionNavigation = new HashSet<tbEstadosCiviles>();
            tbFacturasDetallesfactdeta_UsuCreacionNavigation = new HashSet<tbFacturasDetalles>();
            tbFacturasDetallesfactdeta_UsuModificacionNavigation = new HashSet<tbFacturasDetalles>();
            tbFacturasfact_UsuCreacionNavigation = new HashSet<tbFacturas>();
            tbFacturasfact_UsuModificacionNavigation = new HashSet<tbFacturas>();
            tbMarcasusua_IdCreacionNavigation = new HashSet<tbMarcas>();
            tbMarcasusua_IdModificacionNavigation = new HashSet<tbMarcas>();
            tbMetodosPagometo_UsuCreacionNavigation = new HashSet<tbMetodosPago>();
            tbMetodosPagometo_UsuModificacionNavigation = new HashSet<tbMetodosPago>();
            tbMunicipiosmuni_UsuCreacionNavigation = new HashSet<tbMunicipios>();
            tbMunicipiosmuni_UsuModificacionNavigation = new HashSet<tbMunicipios>();
            tbOrdenesusua_IdCreacionNavigation = new HashSet<tbOrdenes>();
            tbOrdenesusua_IdModificacionNavigation = new HashSet<tbOrdenes>();
            tbPantallasPorRolespantrole_UsuCreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolespantrole_UsuModificacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbProveedoresprov_UsuCreacionNavigation = new HashSet<tbProveedores>();
            tbProveedoresprov_UsuModificacionNavigation = new HashSet<tbProveedores>();
            tbRolesrole_UsuCreacionNavigation = new HashSet<tbRoles>();
            tbRolesrole_UsuModificacionNavigation = new HashSet<tbRoles>();
            tbSucursalessucu_UsuCreacionNavigation = new HashSet<tbSucursales>();
            tbSucursalessucu_UsuModificacionNavigation = new HashSet<tbSucursales>();
        }

        public int usua_Id { get; set; }
        public string usua_NombreUsuario { get; set; }
        public string usua_Contrasena { get; set; }
        public bool? usua_EsAdmin { get; set; }
        public int? role_Id { get; set; }
        public int? empe_Id { get; set; }
        public int? usua_UsuCreacion { get; set; }
        public DateTime usua_FechaCreacion { get; set; }
        public int? usua_UsuModificacion { get; set; }
        public DateTime? usua_FechaModificacion { get; set; }
        public bool? usua_Estado { get; set; }

        [NotMapped]
        public int sucu_Id { get; set; }
        public virtual tbEmpleados empe { get; set; }
        public virtual tbRoles role { get; set; }
        public virtual tbUsuarios usua_UsuCreacionNavigation { get; set; }
        public virtual tbUsuarios usua_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> Inverseusua_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbAros> tbArosaros_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbAros> tbArosaros_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbCargos> tbCargoscarg_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriascate_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbCategorias> tbCategoriascate_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbCitas> tbCitasusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbCitas> tbCitasusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesclie_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbConsultorios> tbConsultoriosusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbConsultorios> tbConsultoriosusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbDepartamentos> tbDepartamentosdepa_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbDetallesCitas> tbDetallesCitasusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbDetallesCitas> tbDetallesCitasusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbDetallesEnvios> tbDetallesEnviosusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbDetallesEnvios> tbDetallesEnviosusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbDetallesOrdenes> tbDetallesOrdenesusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbDetallesOrdenes> tbDetallesOrdenesusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbDireccionesPorCliente> tbDireccionesPorClienteusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbDireccionesPorCliente> tbDireccionesPorClienteusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbDirecciones> tbDireccionesusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbDirecciones> tbDireccionesusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempe_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbEmpleados> tbEmpleadosempe_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbEnvios> tbEnviosusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbEnvios> tbEnviosusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestacivi_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesestacivi_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetallesfactdeta_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetallesfactdeta_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfact_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturasfact_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbMarcas> tbMarcasusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbMarcas> tbMarcasusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagometo_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbMetodosPago> tbMetodosPagometo_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbMunicipios> tbMunicipiosmuni_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbOrdenes> tbOrdenesusua_IdCreacionNavigation { get; set; }
        public virtual ICollection<tbOrdenes> tbOrdenesusua_IdModificacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolespantrole_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolespantrole_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresprov_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbProveedores> tbProveedoresprov_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesrole_UsuModificacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UsuCreacionNavigation { get; set; }
        public virtual ICollection<tbSucursales> tbSucursalessucu_UsuModificacionNavigation { get; set; }
    }
}