// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class VW_tbPantallasPorRoles
    {
        public int pantrole_Id { get; set; }
        public int role_Id { get; set; }
        public string pantrole_NombreRol { get; set; }
        public int pant_Id { get; set; }
        public string pantrole_NombrePantalla { get; set; }
        public string pantrole_NombreMenu { get; set; }
        public int pantrole_UsuCreacion { get; set; }
        public DateTime pantrole_FechaCreacion { get; set; }
        public int? pantrole_UsuModificacion { get; set; }
        public DateTime? pantrole_FechaModificacion { get; set; }
        public bool pantrole_Estado { get; set; }
    }
}