// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class VW_tbPantallas
    {
        public int pant_Id { get; set; }
        public string pant_Nombre { get; set; }
        public string pant_Url { get; set; }
        public string pant_Menu { get; set; }
        public string pant_Icon { get; set; }
        public int pant_UsuCreacion { get; set; }
        public string pant_NombreUsuarioCreacion { get; set; }
        public DateTime pant_FechaCreacion { get; set; }
        public int? pant_UsuModificacion { get; set; }
        public string pant_NombreUsuarioModificacio { get; set; }
        public DateTime? pant_FechaModificacion { get; set; }
        public bool pant_Estado { get; set; }
    }
}