// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class VW_tbAros
    {
        public int aros_Id { get; set; }
        public string aros_Descripcion { get; set; }
        public decimal aros_CostoUni { get; set; }
        public int cate_Id { get; set; }
        public string aros_NombreCategoria { get; set; }
        public int prov_Id { get; set; }
        public string aros_NombreProveedor { get; set; }
        public int marc_Id { get; set; }
        public string aros_NombreMarca { get; set; }
        public int aros_UsuCreacion { get; set; }
        public string aros_NombreUsuarioCreacion { get; set; }
        public DateTime aros_FechaCreacion { get; set; }
        public DateTime? aros_FechaModificacion { get; set; }
        public int? aros_UsuModificacion { get; set; }
        public string aros_NombreUsuarioModificacion { get; set; }
        public bool aros_Estado { get; set; }
    }
}