// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class VW_tbRoles
    {
        public int role_Id { get; set; }
        public string role_Nombre { get; set; }
        public int role_UsuCreacion { get; set; }
        public string role_NombreUsuarioCreacion { get; set; }
        public DateTime role_FechaCreacion { get; set; }
        public int? role_UsuModificacion { get; set; }
        public string role_NombreUsuarioModificacion { get; set; }
        public DateTime? role_FechaModificacion { get; set; }

        [NotMapped]
        public int[] role_Pantallas { get; set; }
    }
}