// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class VW_tbMarcas
    {
        public int marc_Id { get; set; }
        public string marc_Nombre { get; set; }
        public bool? marc_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public string marc_NombreUsuarioCreacion { get; set; }
        public DateTime? usua_IdModificacion { get; set; }
        public string marc_NombreUsuarioModificacion { get; set; }
        public DateTime? marc_FechaModificacion { get; set; }
    }
}