// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class VW_tbConsultoriosList
    {
        public int? cons_Id { get; set; }
        public string cons_Nombre { get; set; }
        public bool? cons_Estado { get; set; }
        public int? usua_IdCreacion { get; set; }
        public string cons_NombreUsuarioCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public string cons_NombreUsuarioModificacion { get; set; }
        public DateTime? cons_FechaCreacion { get; set; }
        public DateTime? cons_FechaModificacion { get; set; }
        public int sucu_Id { get; set; }
        public string sucu_Descripcion { get; set; }
    }
}