// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class VW_tbClientes
    {
        public int clie_Id { get; set; }
        public string clie_Nombres { get; set; }
        public string clie_Apellidos { get; set; }
        public string clie_NombreCompleto { get; set; }
        public string clie_Identidad { get; set; }
        public string clie_Sexo { get; set; }
        public DateTime clie_FechaNacimiento { get; set; }
        public int estacivi_Id { get; set; }
        public string clie_EstadoCivilNombre { get; set; }
        public string clie_Telefono { get; set; }
        public string clie_CorreoElectronico { get; set; }
        public int dire_Id { get; set; }
        public string dire_DireccionExacta { get; set; }
        public string muni_Id { get; set; }
        public string sucu_MunicipioNombre { get; set; }
        public string depa_Id { get; set; }
        public int clie_UsuCreacion { get; set; }
        public string clie_NombreUsuarioCreacion { get; set; }
        public DateTime clie_FechaCreacion { get; set; }
        public int? clie_UsuModificacion { get; set; }
        public string clie_NombreUsuarioModificacion { get; set; }
        public DateTime? clie_FechaModificacion { get; set; }
        public bool clie_Estado { get; set; }
    }
}