// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class VW_tbDetallesCitas
    {
        public int deci_Id { get; set; }
        public int cita_Id { get; set; }
        public decimal deci_Costo { get; set; }
        public string deci_HoraInicio { get; set; }
        public string deci_HoraFin { get; set; }
        public bool? deci_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public string deci_NombreUsuarioCreacion { get; set; }
        public DateTime? deci_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public string deci_NombreUsuarioModificacion { get; set; }
        public DateTime? deci_FechaModificacion { get; set; }
    }
}