// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class VW_tbDireccionesPorClientes
    {
        public int dicl_Id { get; set; }
        public int clie_Id { get; set; }
        public string dicl_NombreClientes { get; set; }
        public int dire_Id { get; set; }
        public string dicl_DireccionExacta { get; set; }
        public bool? dicl_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public string dicl_NombreUsuarioCreacion { get; set; }
        public DateTime? clie_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public string dicl_NombreUsuarioModificacion { get; set; }
        public DateTime? clie_FechaModificacion { get; set; }
    }
}