// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace OpticaPopular.Entities.Entities
{
    public partial class VW_tbOrdenes
    {
        public int orde_Id { get; set; }
        public int clie_Id { get; set; }
        public string orde_Fecha { get; set; }
        public DateTime orde_FechaEntrega { get; set; }
        public DateTime? orde_FechaEntregaReal { get; set; }
        public int sucu_Id { get; set; }
        public string orde_Estado { get; set; }
        public int usua_IdCreacion { get; set; }
        public DateTime? orde_FechaCreacion { get; set; }
        public int? usua_IdModificacion { get; set; }
        public DateTime? orde_FechaModificacion { get; set; }
    }
}